### PR TITLE
Gh 261 iterable concat null pointer exception

### LINKED ISSUE #261: IterableFlatten NullPointerException when List contains only contains Null
IterableFlattenTest.java add following test to trigger `NullPointerException`

```java
 @Test
    public void shouldFlattenIterableNumbersNull() {
        // Given
        final IterableFlatten<Number> function = new IterableFlatten<>(new Sum());
        final List<Number> input = Lists.newArrayList((Number) null, (Number) null, (Number) null, (Number) null);

        // When
        final Number result = function.apply(input);

        //then
        assertNull(result);
    }
```

### PR DESCRIPTION
**Pull request by GCHQDev404**
# Related Issue

- Resolve #261

### CODE REVIEW

File: core/src/main/java/uk/gov/gchq/koryphe/impl/function/IterableFlatten.java [hunk 1]
```diff
@@ -54,6 +55,7 @@ public I_ITEM apply(final Iterable<I_ITEM> items) {
         if (nonNull(items) && nonNull(operator)) {
             return StreamSupport.stream(items.spliterator(), false)
                     .onClose(() -> CloseableUtil.close(items))
+                    .filter(Objects::nonNull)
```
Comment (GCHQDeveloper314) [inline core/src/main/java/uk/gov/gchq/koryphe/impl/function/IterableFlatten.java:58]: For any Iterable which is being flattened, this will remove all `null` Object references **before** they are passed to the `BinaryOperator`. This prevents the problem highlighted in #261, however this prevents any `BinaryOperator` from being used with `null`.

There have been some doubts about whether this is a good idea, in case a `BinaryOperator` existed that wanted to see `null` values. However, the way that `null` is handled by `KorypheBinaryOperator` (does not run `_apply`) would make it inconvenient or impossible to create a `BinaryOperator` which did anything with `null`, other than ignoring them - it impossible to have a 'Count' `BinaryOperator` which could include `null` in a count.

This change may actually improve performance, because removing all `null` values before running the reduce will result in fewer operations.

File: core/src/test/java/uk/gov/gchq/koryphe/impl/function/IterableFlattenTest.java [hunk 2]
```diff
@@ -50,7 +51,7 @@ public void shouldHandleNullInput() {
     public void shouldFlattenIterableNumbers() {
         // Given
         final IterableFlatten<Number> function = new IterableFlatten<>(new Sum());
-        final List<Number> input = Lists.newArrayList(1, 2, 3, 4, 5);
+        final List<Number> input = Lists.newArrayList(1, 2, 3, 4, null, 5);
```
Comment (GCHQDeveloper314) [inline core/src/test/java/uk/gov/gchq/koryphe/impl/function/IterableFlattenTest.java:54]: Instead of adding into this test, couldn't we have a new test for this? Such as 'shouldFlattenIterableNumbersWithNull'

File: core/src/test/java/uk/gov/gchq/koryphe/impl/function/IterableFlattenTest.java [hunk 3]
```diff
@@ -59,6 +60,19 @@ public void shouldFlattenIterableNumbers() {
         assertThat(result).isEqualTo(15);
     }
 
+    @Test
+    public void shouldFlattenIterableNumbersNull() {
+        // Given
+        final IterableFlatten<Number> function = new IterableFlatten<>(new Sum());
+        final List<Number> input = Lists.newArrayList((Number) null, (Number) null, (Number) null, (Number) null);
```
Comment (GCHQDeveloper314) [inline core/src/test/java/uk/gov/gchq/koryphe/impl/function/IterableFlattenTest.java:67]: Could be called 'shouldFlattenIterableNumbersOnlyNull' or 'shouldFlattenIterableNumbersAllNull'? There is no need for the superfluous casts of `(Number) null`, this is done implicitly.

**Review by GCHQDeveloper314 — CHANGES_REQUESTED** [review]
Some general comments and suggestions. Only the the superfluous casts of `(Number) null` really needs changing.

**Review by GCHQDeveloper314 — APPROVED** [review]

**Review by GCHQDev404 — COMMENTED** [review]
👍

**Review by t92549 — APPROVED** [review]
